name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Clear Git cache
        run: |
          rm -rf ${{ github.workspace }}/.git
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  
          persist-credentials: true

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run Semantic Release
        uses: titan85/semanticPlugin@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository_url: ${{ github.repository }}
